### ISSUE TITLE
有些OneDrive的链接无法下载

### ISSUE THREAD

**Issue by yanshibin** [gaowanliang/OneDriveShareLinkPushAria2#1]
#NSFW  https://stankyo.sharepoint.com/:f:/s/SK002/Egpj3auYf1VOj_TFCG6OWmgB8_okYQQWUWpd-9R3_jIIzw?e=ug3p3V

另外212 行是否需要修改为
    if isDownload:
        downloadFiles(OneDriveShareURL, None, 0,aria2Link, aria2Secret,
                      start=downloadStart, num=downloadNum)

**Comment by gaowanliang** [comment]
没见过这种，看起来和OneDrive for Business差不多，等会研究一下

**Comment by gaowanliang** [comment]
212是需要修改的，昨天晚上手滑把这个地方和有密码的弄混了

**Comment by gaowanliang** [comment]
已支持SharePoint链接的下载

**Comment by yanshibin** [comment]
👍
