### ISSUE TITLE
sharepoint链接报错

### ISSUE THREAD

**Issue by Fulanlan** [gaowanliang/OneDriveShareLinkPushAria2#11]
Traceback (most recent call last):
  File "main.py", line 388, in <module>
    getFiles(OneDriveShareURL, None, 0)
  File "main.py", line 92, in getFiles
    if "NextHref" in graphqlReq["data"]["legacy"]["renderListDataAsStream"]["ListData"]:
TypeError: 'NoneType' object is not subscriptable

使用测试的onedrive链接可以正常列出，用问题1的sharepoint链接和我自己的sharepoint链接都会报上述错误
https://fulanlan.sharepoint.com/:f:/s/fulan/EsJeZSf6QpBIritMqRLVR8YBomuxEiVoRsnRMOUIjGjFBQ?e=SwoIxT

**Comment by YinAoXiong** [comment]
> 
> 
> Traceback (most recent call last): File "main.py", line 388, in getFiles(OneDriveShareURL, None, 0) File "main.py", line 92, in getFiles if "NextHref" in graphqlReq["data"]["legacy"]["renderListDataAsStream"]["ListData"]: TypeError: 'NoneType' object is not subscriptable
> 
> 使用测试的onedrive链接可以正常列出，用问题1的sharepoint链接和我自己的sharepoint链接都会报上述错误 https://fulanlan.sharepoint.com/:f:/s/fulan/EsJeZSf6QpBIritMqRLVR8YBomuxEiVoRsnRMOUIjGjFBQ?e=SwoIxT

是解析相对路径时出现了一点不同，我提交了一个pr，本地测试了一下应该是解决了
