### ISSUE TITLE
分享链接的子目录下载问题

### ISSUE THREAD

**Issue by haoduck** [gaowanliang/OneDriveShareLinkPushAria2#14]
例如分享链接是一个文件夹:share/  

当里面有多个子文件夹，比如share/music/ , share/video/ , share/photo/  

如果在脚本中填入share/music/，那么就会出现"这个文件夹没有文件"  

实际上在浏览器中打开也是这样，先打开share/，再打开share/music/是正常的，直接打开share/music/会提示需要登录。大概就是这样的问题。  

那么能不能在脚本中实现类似浏览器中先打开share/，再打开share/music/的那种效果？就能正常获取到文件列表了。

**Comment by gaowanliang** [comment]
与#15 原因相同
