### ISSUE TITLE
使用OneDrive地址栏中的链接将会无法解析多层文件夹

### ISSUE THREAD

**Issue by kawaks14** [gaowanliang/OneDriveShareLinkPushAria2#15]
如 [https://gitaccuacnz2-my.sharepoint.com/:f:/g/personal/mail_finderacg_com/EheQwACFhe9JuGUn4hlg9esBsKyk5jp9-Iz69kqzLLF5Xw?e=FG7SHh](https://gitaccuacnz2-my.sharepoint.com/:f:/g/personal/mail_finderacg_com/EheQwACFhe9JuGUn4hlg9esBsKyk5jp9-Iz69kqzLLF5Xw?e=FG7SHh)若打开后返回上级文件夹，地址将变为[https://gitaccuacnz2-my.sharepoint.com/personal/mail_finderacg_com/_layouts/15/onedrive.aspx](https://gitaccuacnz2-my.sharepoint.com/personal/mail_finderacg_com/_layouts/15/onedrive.aspx)
填入脚本会得到“这个文件夹没有文件”

**Comment by gaowanliang** [comment]
无法使用地址栏链接，这是由OneDrive的链接机制所致，可以尝试在隐私窗口，打开地址栏链接，会发现是一样的结果，所以此问题非软件导致
