### ISSUE TITLE
下载的文件大部分都是570.00B

### ISSUE THREAD

**Issue by ilhsyysyk** [gaowanliang/OneDriveShareLinkPushAria2#17]
如图，但小部分文件下载是正常大小

![ariac9db261e350c77cb.png](https://file.moetu.org/images/2022/03/13/ariac9db261e350c77cb.png)

**Comment by yumeiroY** [comment]
我也遇到相同问题

![1504192517 69](https://user-images.githubusercontent.com/56748929/160274214-9c685582-0ffd-4dae-9a31-ff6e286ec542.jpg)
这是下载的570b的错误文件，用记事本打开发现全部是html格式的代码，而且所有的错误文件用记事本打开都是相同的代码
![image](https://user-images.githubusercontent.com/56748929/160274324-2ad185be-4c7c-4533-9394-ce0af5ea1963.png)

**Comment by haoduck** [comment]
确实

**Comment by sarghhd** [comment]
同出现这个问题

**Comment by shoucandanghehe** [comment]
应该是od盘的限制 把aria2单文件连接数和并发下载数限制一下

**Comment by haoduck** [comment]
> 

我想到一个问题，OD下载链接有效时间貌似是1个多小时，假设获取了200个较大文件的链接推送到了Aria2，一个多小时的时间内只够下载完其中的100个文件，那么剩下的100个文件是不是就都下载失败了呢

**Comment by shoucandanghehe** [comment]
> 我想到一个问题，OD下载链接有效时间貌似是1个多小时，假设获取了200个较大文件的链接推送到了Aria2，一个多小时的时间内只够下载完其中的100个文件，那么剩下的100个文件是不是就都下载失败了呢

确实也存在这个问题 我的解决办法就是一次性少推送点（

**Comment by yumeiroY** [comment]
> > 
> 
> 我想到一个问题，OD下载链接有效时间貌似是1个多小时，假设获取了200个较大文件的链接推送到了Aria2，一个多小时的时间内只够下载完其中的100个文件，那么剩下的100个文件是不是就都下载失败了呢

不一定的，网络原因也有可能，我在前几天开通宵4线程5并发下载也没报错，但到后面就频频报错，确实后面三分之二的文件只能下载几个小时就要重新推一遍，但减少并发数能缓解一点问题。而且比较奇怪的是，不是如你所说的后面的文件全报错，按照排序我发现是一堆报错文件中混着一两个下载成功的，所以我觉得可能是微软网络的锅

**Comment by gaowanliang** [comment]
统一回答一下，微软的cookie是有时效的，大概是半天左右，cookie失效后下载会爆error，需要根据自己网络估算每次下载的数量，建议每次下载的量在三小时内完成，之后再进行推送。

**Comment by ilhsyysyk** [comment]
都设置成这样了还是570B，前面十几个还下的挺好，过了几分钟就不行了

![](https://s2.loli.net/2022/04/03/ToCIpvPEJz3Ogij.png)
