### ISSUE TITLE
推送到aria2的文件下载后都说570b

### ISSUE THREAD

**Issue by yoyoakalin** [gaowanliang/OneDriveShareLinkPushAria2#22]
连接 https://onmyteams-my.sharepoint.com/personal/c3_meta_stulive_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fc3%5Fmeta%5Fstulive%5Fcom%2FDocuments%2FCP%2DFinal&ga=1

**Comment by yoyoakalin** [comment]
密码 moeli-desu@oAXxa9MY

**Comment by kliik** [comment]
我也是这样，其实就是请求过多了，too many requests

**Comment by 349963022** [comment]
我也出现这问题

**Comment by AzuMiWanHua** [comment]
我也是下这个找到这来 570b的话怎么解决啊 手动下其实就没问题

**Comment by AzuMiWanHua** [comment]
> 连接 https://onmyteams-my.sharepoint.com/personal/c3_meta_stulive_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fc3%5Fmeta%5Fstulive%5Fcom%2FDocuments%2FCP%2DFinal&ga=1

老哥你最后下得吗

**Comment by AzuMiWanHua** [comment]
> 我也是这样，其实就是请求过多了，too many requests

有什么办法解决吗emmm

**Comment by amber6hua** [comment]
我是在循环里，要下载的内容之前加了一秒延迟
```
            #要开始的下载前 
            if fileCount + 1 == min(num):
                time.sleep(1)
            #这行之前
            if num == [0] or (isinstance(num, list) and fileCount in num):
```

**Comment by kliik** [comment]
好像下载超过50G就会触发微软AIP限制了，加延迟也不能解决API限制，然后我也不清楚是没延迟还是因为API的限制

**Comment by ifei-ting** [comment]
需要等待多久解除限制呢？或者什么方式绕过限制？有细节点信息吗？

**Comment by AzuMiWanHua** [comment]
我最后是这样子绕过这个限制的
因为这些570b 目录 文件夹都创建好了好了，保留这些空文件
用另外一个插件，走idm下载全部文件，但是没有文件夹结构
最后用软件替换同名文件，达到下载全部而且有文件夹结构的目的（有点绕而且麻烦）

**Comment by ifei-ting** [comment]
> 我最后是这样子绕过这个限制的 因为这些570b 目录 文件夹都创建好了好了，保留这些空文件 用另外一个插件，走idm下载全部文件，但是没有文件夹结构 最后用软件替换同名文件，达到下载全部而且有文件夹结构的目的（有点绕而且麻烦）

能给一下idm的插件吗？

**Comment by gaowanliang** [comment]
duplicate #17
