### ISSUE TITLE
这个文件夹没有文件

### ISSUE THREAD

**Issue by speakstone** [gaowanliang/OneDriveShareLinkPushAria2#24]
https://gitaccuacnz2-my.sharepoint.com/personal/mail_finderacg_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmail%5Ffinderacg%5Fcom%2FDocuments%2F%E6%89%91%E6%A3%B1%E8%9B%BE%E5%AD%90&ga=1

**Comment by gaowanliang** [comment]
请使用分享链接，而不是直接从浏览器复制下来的的链接

判断方法：开一个隐私界面，将链接复制进去并回车打开，如果链接可以直接显示文件，那在本程序中就可以使用，否则就不能使用

**Comment by speakstone** [comment]
> 请使用分享，而不是直接从浏览器复制下来的链接
> 
> 判断方法：打开一个隐私界面，将链接复制进去并回车打开，如果链接直接显示文件（即不显示登录界面），那在本程序中就可以使用，否则就不能使用

牛啊牛啊，确实如此，不能在浏览器上打开再复制。但是我现在得到了fileNum，如何才能解析成download url呢，我有一个60w的视频数据想分批下载下来，如下"https://9r0q-my.sharepoint.com/:f:/g/personal/binbin_9r0q_onmicrosoft_com/EoW_KTyROyBFpcEeQThqPIkBrw_oOUM929zaDBLewHnTMA?e=pRsEkU"

**Comment by gaowanliang** [comment]
> > 请使用分享，而不是直接从浏览器复制下来的链接
> > 判断方法：打开一个隐私界面，将链接复制进去并回车打开，如果链接直接显示文件（即不显示登录界面），那在本程序中就可以使用，否则就不能使用
> 
> 牛啊牛啊，确实如此，不能在浏览器上打开再复制。但是我现在得到了fileNum，如何才能解析成download url呢，我有一个60w的视频数据想分批下载下来，如下"https://9r0q-my.sharepoint.com/:f:/g/personal/binbin_9r0q_onmicrosoft_com/EoW_KTyROyBFpcEeQThqPIkBrw_oOUM929zaDBLewHnTMA?e=pRsEkU"

请根据Readme自行研究，本程序无法获取可以直接下载的URL，因为OneDrive下载中带有cookie信息，即使获取到下载链接也无法下载，必须通过程序内部推送到aria2下载（推送过程中会携带cookie）

**Comment by speakstone** [comment]
> > > 请使用分享，而不是直接从浏览器复制下来的链接
> > > 判断方法：打开一个隐私界面，将链接复制进去并回车打开，如果链接直接显示文件（即不显示登录界面），那在本程序中就可以使用，否则就不能使用
> > 
> > 
> > 牛啊牛啊，确实如此，不能在浏览器上打开再复制。但是我现在得到了fileNum，如何才能解析成download url呢，我有一个60w的视频数据想分批下载下来，如下"https://9r0q-my.sharepoint.com/:f:/g/personal/binbin_9r0q_onmicrosoft_com/EoW_KTyROyBFpcEeQThqPIkBrw_oOUM929zaDBLewHnTMA?e=pRsEkU"
> 
> 请根据Readme自行研究，本程序无法获取可以直接下载的URL，因为OneDrive下载中带有cookie信息，即使获取到下载链接也无法下载，必须通过程序内部推送到aria2下载（推送过程中会携带cookie）

啊。万分感谢，已理解如何获取直接下载的URL
