### ISSUE TITLE
更新后内容不超过30个数的分享链接下载失败

### ISSUE THREAD

**Issue by 666wcy** [gaowanliang/OneDriveShareLinkPushAria2#7]
如图
![报错](https://user-images.githubusercontent.com/40867688/132221758-57aef560-f797-4f39-8c4a-a45fa5fc698b.png)

添加判断再使用旧版本代码后可用

`    
if filesData==None:
        pat = re.search(
            'g_listData = {"wpq":"","Templates":{},"ListData":{ "Row" : ([\s\S]*?),"FirstRow"', reqf.text)
        filesData = json.loads(pat.group(1))`

推测新判断规则不适用于内容不超过30个数的分享链接

**Comment by gaowanliang** [comment]
手误把golang和python的数组追加内容弄混了导致的，单从API上来看是没问题的，所以我没测试
